@token = paste_token_here

POST http://localhost:3000/records
Authorization: Bearer {{token}}
content-type: application/json

{
    "amount": 100,
    "type": "INCOME",
    "category": "food",
    "date": "2022-09-27 18:00:00.000",
    "notes": "none"
}