@token = paste_token_here
@recordId = 1

PATCH http://localhost:3000/records/{{recordId}}
Authorization: Bearer {{token}}
content-type: application/json

{
    "amount": 150,
    "type": "EXPENSE",
    "category": "groceries",
    "date": "2022-09-27 18:00:00.000",
    "notes": "bought chocolates"
}
