@token = paste_token_here

GET http://localhost:3000/records
Authorization: Bearer {{token}}

## Filters
##
## ?userId= [ADMIN ACCESS ONLY] [use `all` for accessing global records]
## ?type= [INCOME/EXPENSE]
## ?category= [string value (case-sensitive)]
## ?minAmount= [Number]
## ?maxAmount= [Number]
## ?startDate= [ISO Date]
## ?endDate= [ISO Date]
## ?page= [Number]
## ?limit= [Number (max = 50)]